import re
import math
import numpy as np

# Stylistic markers commonly present in LLM-generated persuasive/phishing text
LLM_DISCOURSE_MARKERS = [
    "kindly be advised", "it is imperative that", "it has come to our attention",
    "please be reminded that", "we appreciate your prompt attention",
    "failure to comply will result in", "in accordance with our security policy",
    "rest assured that", "as part of our ongoing commitment",
    "take immediate action to ensure", "we regret to inform you that",
    "to maintain uninterrupted access", "further action may be required"
]

class AIGeneratedPhishingDetector:
    """
    Novelty Engine: Detects whether phishing communication was generated by Generative AI (LLMs)
    such as ChatGPT/Claude vs Human adversaries.
    Uses stylometry, sentence length variance (burstiness), vocabulary entropy,
    and synthetic structural uniformity.
    """
    def __init__(self):
        self.version = "v1.2.0-genai-phish-detector"
        self.category = "AI-Generated Phishing Forensics"

    def calculate_burstiness(self, text: str) -> float:
        """
        Burstiness measures the variance in sentence lengths.
        Humans naturally vary sentence lengths dramatically (high burstiness).
        LLMs tend to produce uniformly balanced sentences (low burstiness).
        """
        sentences = [s.strip() for s in re.split(r'[.!?]+', text) if len(s.strip()) > 3]
        if len(sentences) < 2:
            return 0.5  # Neutral default for very short texts
            
        lengths = [len(s.split()) for s in sentences]
        mean_len = float(np.mean(lengths))
        std_len = float(np.std(lengths))
        
        # Coefficient of variation (CV = std / mean)
        cv = (std_len / max(1.0, mean_len))
        return round(cv, 3)

    def calculate_lexical_diversity(self, text: str) -> float:
        """Type-Token Ratio (TTR) with token-frequency distribution."""
        words = re.findall(r'\b[a-zA-Z]+\b', text.lower())
        if not words:
            return 0.0
        unique_words = len(set(words))
        return round(unique_words / len(words), 3)

    def analyze(self, text: str) -> dict:
        text_clean = text.strip()
        words = re.findall(r'\b[a-zA-Z]+\b', text_clean.lower())
        word_count = len(words)
        
        # 1. Burstiness (sentence variation)
        burstiness = self.calculate_burstiness(text_clean)
        
        # 2. Lexical diversity
        lex_div = self.calculate_lexical_diversity(text_clean)
        
        # 3. LLM discourse markers check
        matched_markers = [m for m in LLM_DISCOURSE_MARKERS if m in text_clean.lower()]
        
        # 4. Syntactic perfection / Grammar penalty
        # AI text has virtually zero spelling errors and strictly balanced punctuation
        spelling_flaws = len(re.findall(r'\b[a-z]+(?:\d|[_\-]{2,})[a-z]*\b', text_clean))
        
        # Calculate AI generation probability score
        ai_signals = 0.0
        indicators = []
        
        # Low burstiness is a strong hallmark of GenAI
        if burstiness < 0.45 and word_count > 25:
            ai_signals += 0.35
            indicators.append(f"Low structural burstiness ({burstiness} sentence CV): Uniform sentence cadence typical of Large Language Model generation")
        elif burstiness > 0.8:
            ai_signals -= 0.20
            
        if len(matched_markers) >= 2:
            ai_signals += min(0.40, len(matched_markers) * 0.15)
            indicators.append(f"Polished GenAI persuasive discourse markers: '{', '.join(matched_markers[:3])}'")

        if lex_div > 0.65 and word_count > 30 and spelling_flaws == 0:
            ai_signals += 0.25
            indicators.append("High vocabulary consistency with zero orthographic/syntactic imperfections (Synthetic Fluency)")

        base_ai_prob = min(0.96, max(0.08, 0.25 + ai_signals))
        is_ai_generated = base_ai_prob >= 0.60

        return {
            "ai_generated_probability": round(base_ai_prob, 2),
            "is_likely_ai_generated": is_ai_generated,
            "stylometric_metrics": {
                "burstiness_score": burstiness,
                "lexical_diversity": lex_div,
                "word_count": word_count,
                "discourse_markers_count": len(matched_markers)
            },
            "forensic_label": "GenAI-Synthesized Phishing Campaign" if is_ai_generated else "Human-Authored Threat Communication",
            "indicators": indicators if indicators else ["Communication displays natural human variance and informal syntactical pacing."]
        }

ai_phishing_detector = AIGeneratedPhishingDetector()
